title: 'Research Scholars, IIT Madras'
author: 'Research Affairs Secretary, IIT Madras'
email: 'sec_resaf@smail.iitm.ac.in'
description: > # this means to ignore newlines until "show_excerpts:"
  Here we can write an awesome description this site here. We can easily edit this
  line in _config.yml. This description will also appear in 
  Google search results and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# social links
# DO NOT include the @ character, or else the build will fail!
instagram_username: iitmresaff
linkedin_username: iitmresearchaffairs
youtube_username: IIT Madras Research Affairs

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - about.md

# Build settings
theme: minima

plugins:
  - jekyll-seo-tag
